### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by testusuke** [testusuke/line-reminder-bot#2]
- [x] Activate line api
- [x] Creating db tables
- [x] Implement push notification
- [ ] Creating API(token-based)
